/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ultracrm.oborud;

import ultracrm.dogovor.*;
import javax.swing.JOptionPane;
import ultracrm.DatabaseTableModel;
import ultracrm.FilterXML;
import ultracrm.MainFrame;
import ultracrm.Start;
import ultracrm.dogovor.AddDogovor;

/**
 *
 * @author Asus
 */
public class JPanelOborud extends javax.swing.JPanel {

    private DatabaseTableModel dbm = new DatabaseTableModel(false);

    /**
     * Creates new form JPanelKontr
     */
    public JPanelOborud() {
   
        initComponents();
        try {
            dbm.setDataSource(Start.mf.sDb.getDOborud());
        } catch (Exception ex) {
            System.out.println("Создание таблицы перенаправленные ошибка доступа к RS" + ex);
        }

        dOborudTable.getColumnModel().getColumn(0).setPreferredWidth(40);
        dOborudTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        dOborudTable.getColumnModel().getColumn(2).setPreferredWidth(250);
        dOborudTable.getColumnModel().getColumn(3).setPreferredWidth(80);
//       dOborudTable.getColumnModel().getColumn(4).setPreferredWidth(80);
//        dOborudTable.getColumnModel().getColumn(5).setPreferredWidth(800);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        butAdd = new javax.swing.JButton();
        butUpdate = new javax.swing.JButton();
        butDel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dOborudTable = new javax.swing.JTable();

        fileChooser.setDialogTitle("Выбор файла для импорта");
        fileChooser.setFileFilter(new FilterXML());

        butAdd.setText("Добавить");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });

        butUpdate.setText("Редактировать");
        butUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butUpdateActionPerformed(evt);
            }
        });

        butDel.setText("Удалить");
        butDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDelActionPerformed(evt);
            }
        });

        dOborudTable.setAutoCreateRowSorter(true);
        dOborudTable.setModel(dbm);
        dOborudTable.setToolTipText("");
        dOborudTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dOborudTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dOborudTableMouseEntered(evt);
            }
        });
        dOborudTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(dOborudTable);
        dOborudTable.setFocusable(false);
        dOborudTable.getTableHeader().setReorderingAllowed(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(butAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butDel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1054, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAdd)
                    .addComponent(butUpdate)
                    .addComponent(butDel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
        AddOborud addForm = new AddOborud(Start.mf, true, "Добавление нового оборудования", null);
        addForm.setVisible(true);
    }//GEN-LAST:event_butAddActionPerformed

    private void butUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butUpdateActionPerformed
        if (dOborudTable.getSelectedRow() != -1) {
            DDogovor dog = MainFrame.sDb.getDogovor((int) dOborudTable.getValueAt(dOborudTable.getSelectedRow(), 0));
            AddDogovor addForm = new AddDogovor(Start.mf, true, "Редактирование договора", dog);
            addForm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Необходимо выделить договор", "Внимание", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_butUpdateActionPerformed

    private void butDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butDelActionPerformed

    private void dOborudTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dOborudTableMouseClicked
        if (evt.getClickCount() == 2) {
            DDogovor dog = MainFrame.sDb.getDogovor((int) dOborudTable.getValueAt(dOborudTable.getSelectedRow(), 0));
            AddDogovor addForm = new AddDogovor(Start.mf, true, "Редактирование договора", dog);
            addForm.setVisible(true);
        }
    }//GEN-LAST:event_dOborudTableMouseClicked

    private void dOborudTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dOborudTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dOborudTableMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAdd;
    private javax.swing.JButton butDel;
    private javax.swing.JButton butUpdate;
    private javax.swing.JTable dOborudTable;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
