/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ultracrm.treker;

import java.awt.Desktop;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import ultracrm.dogovor.*;
import ultracrm.kontragent.*;
import javax.swing.JOptionPane;
import ultracrm.MainFrame;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import yandexPack.YandexRequest;

/**
 *
 * @author Asus
 */
public class CheckGeo extends javax.swing.JDialog {

    private Device dev;

    /**
     * Creates new form AddKontr
     */
    public CheckGeo(java.awt.Frame parent, boolean modal, String title, Device dev) {
        super(parent, modal);
        initComponents();
        this.dev = dev;
        this.setTitle(title);
        this.jLabelTrackerId.setText(dev.getId());
        //MainFrame.sDb.getCellKoordinats(dev.getId());

        this.cellIdData.setText(MainFrame.sDb.getCellKoordinats(dev.getId()));

        this.gpsData.setText(MainFrame.sDb.getGPSKoordinats(dev.getId()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        jLabelTrackerId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cellIdData = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        butCancel = new javax.swing.JButton();
        butGetAdress = new javax.swing.JButton();
        balans = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gpsData = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        adressData = new javax.swing.JTextField();
        openMapInBrowserForCellid = new javax.swing.JButton();
        adressDataPrecious = new javax.swing.JTextField();
        butGetAdressByGPS = new javax.swing.JButton();
        openMapInBrowserForGPS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelTrackerId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTrackerId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTrackerId.setText("Id трекера");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Данные CellId");

        cellIdData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cellIdData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellIdDataActionPerformed(evt);
            }
        });

        butCancel.setText("Закрыть");
        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        butGetAdress.setText("Получить адрес");
        butGetAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGetAdressActionPerformed(evt);
            }
        });

        balans.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Данные GPS(если есть)");

        gpsData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gpsData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpsDataActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Трекер");

        adressData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adressData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressDataActionPerformed(evt);
            }
        });

        openMapInBrowserForCellid.setText("Посмотреть на карте");
        openMapInBrowserForCellid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMapInBrowserForCellidActionPerformed(evt);
            }
        });

        adressDataPrecious.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adressDataPrecious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressDataPreciousActionPerformed(evt);
            }
        });

        butGetAdressByGPS.setText("Получить точный адрес");
        butGetAdressByGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGetAdressByGPSActionPerformed(evt);
            }
        });

        openMapInBrowserForGPS.setText("Посмотреть на карте");
        openMapInBrowserForGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMapInBrowserForGPSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabelTrackerId, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cellIdData, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(gpsData, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(butGetAdress)
                        .addGap(245, 245, 245)
                        .addComponent(openMapInBrowserForCellid, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(adressData, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(butGetAdressByGPS)
                        .addGap(205, 205, 205)
                        .addComponent(openMapInBrowserForGPS, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(adressDataPrecious, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(balans, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(butCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTrackerId, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(id)))
                .addGap(3, 3, 3)
                .addComponent(cellIdData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(gpsData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butGetAdress)
                    .addComponent(openMapInBrowserForCellid))
                .addGap(7, 7, 7)
                .addComponent(adressData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butGetAdressByGPS)
                    .addComponent(openMapInBrowserForGPS))
                .addGap(7, 7, 7)
                .addComponent(adressDataPrecious, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(butCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balans)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cellIdDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellIdDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellIdDataActionPerformed

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
      
            dispose();
    }//GEN-LAST:event_butCancelActionPerformed

    private void butGetAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGetAdressActionPerformed
        YandexRequest yr = new YandexRequest();
        adressData.setText(yr.getLocation(MainFrame.sDb.getCellKoordinats(dev.getId()), false));
        adressData.updateUI();
    }//GEN-LAST:event_butGetAdressActionPerformed

    private void gpsDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpsDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpsDataActionPerformed

    private void adressDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressDataActionPerformed

    private void openMapInBrowserForCellidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMapInBrowserForCellidActionPerformed
        YandexRequest yr = new YandexRequest();
        String cellCoordinates = yr.getCellLocation(MainFrame.sDb.getCellKoordinats(dev.getId()));
        System.out.println("cellCoordinates=" + cellCoordinates);
        String request = "?text=" + cellCoordinates.split(";")[0] + "%2C" + cellCoordinates.split(";")[1];
        openMapInBrouser(request);
    }//GEN-LAST:event_openMapInBrowserForCellidActionPerformed

    private void adressDataPreciousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressDataPreciousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressDataPreciousActionPerformed

    private void butGetAdressByGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGetAdressByGPSActionPerformed
        YandexRequest yr = new YandexRequest();
        adressDataPrecious.setText(yr.getLocation(MainFrame.sDb.getGPSKoordinats(dev.getId()), true));
        adressDataPrecious.updateUI();
    }//GEN-LAST:event_butGetAdressByGPSActionPerformed

    private void openMapInBrowserForGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMapInBrowserForGPSActionPerformed
        String coordintaes = MainFrame.sDb.getGPSKoordinats(dev.getId());
        String N = coordintaes.split(";")[0];
        String NvalS = N.split(",")[0];
        System.out.println("NvalS=" + NvalS);
        String E = coordintaes.split(";")[1];
        String EvalS = E.split(",")[0];
        System.out.println("EvalS=" + EvalS);
        String request = "?text=" + NvalS + "%2CN%3B" + EvalS + "%2CE";
        openMapInBrouser(request);
    }//GEN-LAST:event_openMapInBrowserForGPSActionPerformed
    private static void openWebpagebyURI(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(uri);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private static void openWebpage(URL url) {
        try {
            openWebpagebyURI(url.toURI());
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    }

    private void openMapInBrouser(String request) {
        URL mapurl = null;
        try {
            https://maps.yandex.ru/213/moscow/?text=5539.9671%2CN%3B03728.2273%2CE
            mapurl = new URL("https://maps.yandex.ru/213/moscow/" + request);
        } catch (MalformedURLException ex) {
            Logger.getLogger(CheckGeo.class.getName()).log(Level.SEVERE, null, ex);
        }
        openWebpage(mapurl);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckGeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckGeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckGeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckGeo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CheckGeo dialog = new CheckGeo(new javax.swing.JFrame(), true, "", null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adressData;
    private javax.swing.JTextField adressDataPrecious;
    private javax.swing.JLabel balans;
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butGetAdress;
    private javax.swing.JButton butGetAdressByGPS;
    private javax.swing.JTextField cellIdData;
    private javax.swing.JTextField gpsData;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTrackerId;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton openMapInBrowserForCellid;
    private javax.swing.JButton openMapInBrowserForGPS;
    // End of variables declaration//GEN-END:variables
}
